### ISSUE TITLE
Set up Site24x7 monitors

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/princeton-manifold#26]
## Acceptance Criteria 

- [x] A Site24x7 web monitor has been set up and configured 
- [x] PagerDuty integration has been tested

**Comment by aprilrieger** [comment]
https://www.site24x7.com/app/client#/home/monitors/195989000075619019/Summary
tested alert: https://assaydepot.slack.com/archives/C03CA8XRP3L/p1726610071178399
