### ISSUE TITLE
Rework prod to use requests instead of sockets

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/princeton-manifold#3]
# Story

By default, the Manifold application relies on sockets to communicate between services (e.g. between the client (frontend) and API (backend)). 

This restricts how we can deploy to our infra. Most importantly, all services that communicate across sockets must be in the same pod. This prevents us from being able to scale horizontally. 

The application code should be altered to allow for services to communicate with each other using requests rather than sockets. 

# Implementation Suggestions 

_Loose steps:_

1. Add k8 Services for cable and client
2. Split deployment into API, client, nginx
3. Change the labels in the services to match the new deployments (unique names)
4. Change nginx configuration to use ports instead of unix sockets<sup>1</sup>
    4a) See `nginx/config/default.conf`

<sup>1</sup> See code below 

```nginx
upstream manifold_api {
  server unix:/manifold_sockets/manifold-api;
  # Replace sockets with this pattern (syntax may be incorrect):
  # server princeton-manifold-api:3020
 }
```

**Comment by jillpe** [comment]
We need this to be completed before the site is officially live - we could potentially have this be the first thing we do in the maintenance contract

**Comment by bkiahstroud** [comment]
So far, the client has not encountered any new issues since this ticket was completed
