### ISSUE TITLE
Configure SMTP mailer settings

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/princeton-manifold#4]
# Story

The application currently attempts to send emails using Sendmail, which throws an error. 

Instead, we want to configure the application to send emails via SMTP. Relevant settings can be found here: 

- https://princeton-manifold-production.softserv.cloud/backend/settings/email 

_(If configuring SMTP via the application settings, verify the settings persist between r2 pod restarts / deployments)_ 

Credentials are in 1Password title: `SMTP Info for Manifold OpenPublishing`

**Comment by aprilrieger** [comment]
What are we using to get smtp setup? Does the client have any of these handy?

- EMAIL REPLY-TO ADDRESS
- EMAIL REPLY-TO NAME
- EMAIL FROM NAME
- EMAIL FROM ADDRESS

- SMTP USERNAME
- SMTP PORT
- SMTP ADDRESS
- SMTP PASSWORD

**Comment by aprilrieger** [comment]
What are we using to get smtp setup? Does the client have any of these handy?

- EMAIL REPLY-TO ADDRESS
- EMAIL REPLY-TO NAME
- EMAIL FROM NAME
- EMAIL FROM ADDRESS

- SMTP USERNAME
- SMTP PORT
- SMTP ADDRESS
- SMTP PASSWORD
<details>
  <summary>Click to expand/collapse screenshots</summary>
<img width="1203" alt="Screenshot 2024-07-11 at 12 32 43" src="https://github.com/scientist-softserv/princeton-manifold/assets/63515648/b206f2ac-a162-4f46-bb8b-51dcb393a9fe">
<img width="1216" alt="Screenshot 2024-07-11 at 12 35 14" src="https://github.com/scientist-softserv/princeton-manifold/assets/63515648/b3f4f376-e5bb-4d9e-ab5f-62288275d09b">

</details>

**Comment by aprilrieger** [comment]
Email sent to client requesting information
<img width="532" alt="Screenshot 2024-07-11 at 14 34 27" src="https://github.com/user-attachments/assets/fd93b5e5-6959-4514-b877-d602b8dd1752">

**Comment by bkiahstroud** [comment]
Client should be sending over all info for this today except the password. The password will be provided ASAP

**Comment by kelynch** [comment]
Details here - https://docs.google.com/document/d/15FT3UHb1QHEVTQsPOJNgOe9T9KCx93uDxkVJ-s6Rs54/edit

**Comment by aprilrieger** [comment]
@kelynch Thank you, I have requested access to the document from my april@scientist.com email.

**Comment by aprilrieger** [comment]
Received access to the document shared, I am unblocked now.

**Comment by aprilrieger** [comment]
Needing the SMTP PASSWORD
Coming from Hannah separately
Blocked till I hear back with password.

**Comment by aprilrieger** [comment]
Unblocked and in 1password title: SMTP Info for Manifold OpenPublishing.

**Comment by aprilrieger** [comment]
@bkiahstroud I didn't get around to this, but I can def try on Monday. A priority ticket got unblocked and I wanted to get a script running over the weekend.

**Comment by bkiahstroud** [comment]
Attempting to send mail using the first SMTP address provided (`lib-ponyexpr-prod.princeton.edu`) throws this error:

```ruby
TestMailer.test(current_user).deliver_now

I, [2024-09-27T17:50:26.595647 #10916]  INFO -- : Delivered mail 66f6f04490b23_2aa42a8052575@princeton-manifold-production-api-rails-855d867c85-t2p5f.mail (30003.4ms)
APIExceptions::StandardError: Manifold was unable to send the email. The exception was of the type
           "Net::OpenTimeout." The message was "execution expired." Double check your
          configuration.
from /opt/manifold/api/lib/dynamic_mailer/mailer.rb:39:in `handle_exception'
Caused by Net::OpenTimeout: execution expired
from /usr/local/bundle/gems/net-smtp-0.4.0/lib/net/smtp.rb:631:in `initialize'
```

Attempting to use the fallback SMTP address provided (`smtp.princeton.edu`) results in this error: 

```ruby
TestMailer.test(current_user).deliver_now

I, [2024-09-27T17:57:25.064078 #10916]  INFO -- : Delivered mail 66f6f20214634_2aa42a805272e@princeton-manifold-production-api-rails-855d867c85-t2p5f.mail (2980.9ms)
APIExceptions::StandardError: Manifold wasn't able to authenticate against the SMTP server using the stored credentials.
from /opt/manifold/api/lib/dynamic_mailer/mailer.rb:39:in `handle_exception'
Caused by Net::SMTPAuthenticationError: Net::SMTPAuthenticationError
from /usr/local/bundle/gems/net-smtp-0.4.0/lib/net/smtp/authenticator.rb:34:in `finish'
```

**Comment by kelynch** [comment]
We're using the lib-openpublish Service account credentials.

**Comment by bkiahstroud** [comment]
Oh hold pending confirmation of values from client

**Comment by kelynch** [comment]
Different values sent securely, let me know if you cannot access.

**Comment by bkiahstroud** [comment]
After logging in as an admin, I clicked the "Send test email" button at the bottom of [this page](https://openpublishing.princeton.edu/backend/settings/email) and received it successfully 🎉 

This is ready for client QA
