### ISSUE TITLE
Implement CAS authentication

### ISSUE THREAD

**Issue by bkiahstroud** [scientist-softserv/princeton-manifold#5]

**Comment by jillpe** [comment]
https://github.com/pulibrary/pul-it-handbook/blob/main/services/cas.md - Here is the information that the princeton developers use to get CAS integration running using omni-auth

**Comment by jillpe** [comment]
Hannah and Kate can help test with their login credentials

**Comment by bkiahstroud** [comment]
Will be using this gem: https://github.com/dlindahl/omniauth-cas

**Comment by bkiahstroud** [comment]
### Work so far 
- https://github.com/scientist-softserv/princeton-manifold/pull/15 
- https://github.com/scientist-softserv/princeton-manifold/pull/16 
- https://github.com/scientist-softserv/princeton-manifold/commit/47067d8226e60c623131f42c4579c17285d7c2af 

### Current status 

Seeing these validation errors after authenticating via CAS: 

> Email can't be blank
> Email is not valid
> First name can't be blank
> Last name can't be blank

<details><summary>Screenshot</summary>

![Image](https://github.com/user-attachments/assets/f8593c62-f789-420f-ba02-df2b9723abed)

</details>

**Comment by bkiahstroud** [comment]
### Update 

Logging in via CAS [is working using](https://github.com/scientist-softserv/princeton-manifold/pull/18) my guest Princeton account. Getting the OAuth config file deployed [was tricky](https://github.com/scientist-softserv/princeton-manifold/pull/19), but that [has been resolved](https://github.com/scientist-softserv/princeton-manifold/pull/20). 

I believe the only (potential) thing left is getting the Princeton logo to render in the CAS button instead of a generic key icon (see screenshot) 

<details><summary>Screenshot</summary>

![Image](https://github.com/user-attachments/assets/90e52637-02b9-4eb5-bad3-055acc55b57b)

</details>

**Comment by bkiahstroud** [comment]
Client confirmed this is working
